using System;
using System.Collections.Generic;

namespace LobotJR.Command
{
    /// <summary>
    /// Class containing the results of an attempt to process a command.
    /// </summary>
    public class CommandResult
    {
        /// <summary>
        /// Whether or not the message matched a loaded command, and that command was executed.
        /// </summary>
        public bool Processed { get; set; }
        /// <summary>
        /// The responses to send back to the user who issued the command.
        /// </summary>
        public IList<string> Responses { get; set; }
        /// <summary>
        /// Messages to send to chat as a result of this command.
        /// </summary>
        public IList<string> Messages { get; set; }
        /// <summary>
        /// Errors generated by the command, regardless of the success of the command's execution.
        /// </summary>
        public IList<Exception> Errors { get; set; }

        public CommandResult()
        {
            Processed = false;
        }

        public CommandResult(params string[] responses)
        {
            Processed = true;
            Responses = new List<string>(responses);
        }

        public CommandResult(bool processed, IEnumerable<Exception> errors)
        {
            Processed = processed;
            if (errors != null)
            {
                Errors = new List<Exception>(errors);
            }
        }
    }
}
